FACTS = {
    "Economy": [
        "'Capitalism is God's way of determining who is smart and who is poor' - Ron Swanson",
        "'Socialism in general has a record of failure so blatant that only an intellectual could ignore or evade it' - Thomas Sowell",
        "'Poor kids are just as bright and just as talented as white kids' - Joe Biden",
        "'You cannot go to a 7-11 or a Dunkin' Donuts unless you have a slight Indian accent' - Joe Biden",
        "'Cars don't cause pollution, trees do' - Ronald Reagan",
        "'Luck is a concept invented by the weak to explain their failures' - Ron Swanson",
        "Did you know: It’s illegal to fall asleep while lying down in a cheese factory in South Dakota",
        "Did you know: Paying people to donate blood statistically makes less people donate blood",
        "‘This is like The Shawshank Redemption, only with more tunneling through shit and no fucking redemption’ - Malcom Tucker",
    ],
    "Government": [
        "'I promise you, the president has a big stick' - Joe Biden",
        'Did you know: China censored the word for "censorship."',
        "Did you know: Hunting unicorns is legal in Michigan.",
        "'You don't reason with intellectuals. You shoot them' - Napoleon Bonaparte",
        "Did you know: Handling salmon suspiciously is a crime in the UK",
        "'I have as much chance of becoming Prime Minister as of being decapitated by a frisbee or of finding Elvis on Mars' - Boris Johnson",
        "Did you know: The British constituency of Old Sarum only had an electorate of one",
        "Did you know: It is illegal to eat oranges in the bath in California",
        "‘They're eating the dogs, the people that came in, they're eating the cats’ - Donald J Trump",
        "'I don’t want to be rude but, really, you have the charisma of a damp rag and the appearance of a low-grade bank clerk.' - Nigel Farage",
        "'I can tell you that bleach will kill the virus in five minutes' - Donald J Trump",
        "Did you know: Australia once had a Prime Minister disappear while swimming",
    ],
    "Society": [
        "'It is a well-known fact that reality has a liberal bias' - Stephen Colbert",
        "'It takes a village to raise a child and somebody said it takes a village idiot to believe that' - Thomas Sowell",
        "'If gay marriage was OK … then I saw no reason in principle why a union should not be consecrated between three men, as well as two men; or indeed three men and a dog.' - Boris Johnson",
        "'It's better not to argue with women' - Putin",
        "'I've never taken drugs, I once ate a jaffa cake whole and I thought I saw God' - Theresa May",
        "Did you know: Conservative MP Stephen Milligan was found dead wearing women's stockings during a botched auto-erotic asphyxiation experiment on his kitchen table",
        "‘How is it even possible to rape a prostitute?’ - Andrzej Lepper",
        "‘There is no such thing as society’ - Margaret Thatcher",
    ],
    "Culture": [
        "Did you know: April 6th is Woodrow Wilson Hate Day",
        "'Mr Trump is friends with Mr [Piers] Morgan and Mr Putin, so he keeps very fine company' - Jacob Reese-Mogg",
        "'Women have always been the primary victim of war' - Hillary Clinton",
        "‘Our enemies are innovative and resourceful, and so are we. They never stop thinking about new ways to harm our country and our people, and neither do we’ - George Bush",
        "'Barack America!' - Joe Biden",
        "'I am a jammy donut' - John F Kennedy",
        "'The problem with quotes from the internet is that they are often not true' - Adolf Hitler",
        "Did you know: No relevance whatsoever, but 11% of Americans think HTML is a disease",
        "'A zebra does not change its spots' - Al Gore",
        "Did you know: In 2001, a survey found that more than one in five British children believed that Sherlock Holmes was a real person.",
    ],
}
